server:
  port: 9091

spring:
  application:
    name: MappingAPI
  datasource:
    username: system
    password: 31082002
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      #database-platform: org.hibernate.dialect.Oracle10gDialect
