server:
  port: 7777

spring:
  application:
    name: ReviewProject

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/sqldb
      username: root
      password: 31082002
      driver-class-name: com.mysql.cj.jdbc.Driver

    oracle:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: system
      password: 31082002
      driver-class-name: oracle.jdbc.driver.OracleDriver
