server:
  port: 1331
spring:
  mail:
    imap:
      user: abhay.eidiko@gmail.com
      password: ${APP_PASSWORD}
      host: imap.gmail.com
      port: 993
      protocol: imaps
      ssl-enable: true

    username: abhay.eidiko@gmail.com
    password: ${APP_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true