server:
  port: 9556

spring:
  mail:
    username: abhaybadwaik.eidiko@gmail.com
    password: ${APP_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true




