server:
  port: 1331
spring:
  application:
    name: SpringSecurity
  datasource:
    username: system
    password: 31082002
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true