server:
  port: 8888

spring:
  mail:
    imap:
      user: abhay.eidiko@gmail.com
      password: ${APP_PASSWORD}
      host: imap.gmail.com
      port: 993
      protocol: imaps
      ssl.enable: true

message:
  folder:
    - "INBOX"
    - "[Gmail]/All Mail"
    - "[Gmail]/Drafts"
    - "[Gmail]/Important"
    - "[Gmail]/Sent Mail"
    - "[Gmail]/Spam"
    - "[Gmail]/Starred"
    - "[Gmail]/Trash"
